# 1.image
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# 2 install dependency
RUN npm install

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]