# 1.from base image
FROM python:3.10-slim

# 2. cretae file
WORKDIR /app

# 3.requiremnt.text
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App source
COPY . .

EXPOSE 8000

# DEV mode with auto-reload
CMD ["uvicorn", "TodoBackend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]